### ISSUE TITLE
在yarn monorepo环境中报错：Error: No PostCSS Config found in:

### ISSUE THREAD

**Issue by heavenkiller2018** [Armour/vue-typescript-admin-template#152]
# I'm submitting a

## Current behavior
在yarn monorepo环境中运行出错， 这个问题要怎样解决呢？

```
|  Building for production...

 ERROR  Failed to compile with 10 errors                                                                                          22:30:45
 error  in D:/mycode/devos-mono2/node_modules/codemirror/addon/lint/lint.css

Module build failed (from D:/mycode/devos-mono2/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from D:/mycode/devos-mono2/node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: D:\mycode\devos-mono2\node_modules\codemirror\addon\lint
    at D:\mycode\devos-mono2\node_modules\postcss-load-config\src\index.js:91:15
    at D:\mycode\devos-mono2\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\mycode\devos-mono2\node_modules\postcss-loader\src\index.js:208:9

 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/components/JsonEditor/index.vue?vue&type=script&lang=ts& 7:0-40
 @ ./src/components/JsonEditor/index.vue?vue&type=script&lang=ts&
 @ ./src/components/JsonEditor/index.vue
 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/views/components-demo/json-editor.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/json-editor.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/json-editor.vue
 @ ./src/router/modules/components.ts
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in D:/mycode/devos-mono2/node_modules/codemirror/lib/codemirror.css

Module build failed (from D:/mycode/devos-mono2/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from D:/mycode/devos-mono2/node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: D:\mycode\devos-mono2\node_modules\codemirror\lib
    at D:\mycode\devos-mono2\node_modules\postcss-load-config\src\index.js:91:15
    at D:\mycode\devos-mono2\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\mycode\devos-mono2\node_modules\postcss-loader\src\index.js:208:9

 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/components/JsonEditor/index.vue?vue&type=script&lang=ts& 8:0-39
 @ ./src/components/JsonEditor/index.vue?vue&type=script&lang=ts&
 @ ./src/components/JsonEditor/index.vue
 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/views/components-demo/json-editor.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/json-editor.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/json-editor.vue
 @ ./src/router/modules/components.ts
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in D:/mycode/devos-mono2/node_modules/codemirror/theme/rubyblue.css

Module build failed (from D:/mycode/devos-mono2/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from D:/mycode/devos-mono2/node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: D:\mycode\devos-mono2\node_modules\codemirror\theme
    at D:\mycode\devos-mono2\node_modules\postcss-load-config\src\index.js:91:15
    at D:\mycode\devos-mono2\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\mycode\devos-mono2\node_modules\postcss-loader\src\index.js:208:9

 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/components/JsonEditor/index.vue?vue&type=script&lang=ts& 9:0-39
 @ ./src/components/JsonEditor/index.vue?vue&type=script&lang=ts&
 @ ./src/components/JsonEditor/index.vue
 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/views/components-demo/json-editor.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/json-editor.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/json-editor.vue
 @ ./src/router/modules/components.ts
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in D:/mycode/devos-mono2/node_modules/driver.js/dist/driver.min.css

Module build failed (from D:/mycode/devos-mono2/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from D:/mycode/devos-mono2/node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: D:\mycode\devos-mono2\node_modules\driver.js\dist
    at D:\mycode\devos-mono2\node_modules\postcss-load-config\src\index.js:91:15
    at D:\mycode\devos-mono2\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\mycode\devos-mono2\node_modules\postcss-loader\src\index.js:208:9

 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/views/guide/index.vue?vue&type=script&lang=ts& 7:0-39
 @ ./src/views/guide/index.vue?vue&type=script&lang=ts&
 @ ./src/views/guide/index.vue
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in D:/mycode/devos-mono2/node_modules/normalize.css/normalize.css

Module build failed (from D:/mycode/devos-mono2/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from D:/mycode/devos-mono2/node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: D:\mycode\devos-mono2\node_modules\normalize.css
    at D:\mycode\devos-mono2\node_modules\postcss-load-config\src\index.js:91:15
    at D:\mycode\devos-mono2\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\mycode\devos-mono2\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.ts 10:0-23
 @ multi ./src/main.ts

 error  in D:/mycode/devos-mono2/node_modules/nprogress/nprogress.css

Module build failed (from D:/mycode/devos-mono2/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from D:/mycode/devos-mono2/node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: D:\mycode\devos-mono2\node_modules\nprogress
    at D:\mycode\devos-mono2\node_modules\postcss-load-config\src\index.js:91:15
    at D:\mycode\devos-mono2\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\mycode\devos-mono2\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/permission.ts 8:0-33
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in D:/mycode/devos-mono2/node_modules/tui-editor/dist/tui-editor-contents.css

Module build failed (from D:/mycode/devos-mono2/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from D:/mycode/devos-mono2/node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: D:\mycode\devos-mono2\node_modules\tui-editor\dist
    at D:\mycode\devos-mono2\node_modules\postcss-load-config\src\index.js:91:15
    at D:\mycode\devos-mono2\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\mycode\devos-mono2\node_modules\postcss-loader\src\index.js:208:9

 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/components/MarkdownEditor/index.vue?vue&type=script&lang=ts& 12:0-49
 @ ./src/components/MarkdownEditor/index.vue?vue&type=script&lang=ts&
 @ ./src/components/MarkdownEditor/index.vue
 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/views/components-demo/markdown.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/markdown.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/markdown.vue
 @ ./src/router/modules/components.ts
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in D:/mycode/devos-mono2/node_modules/tui-editor/dist/tui-editor.css

Module build failed (from D:/mycode/devos-mono2/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from D:/mycode/devos-mono2/node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: D:\mycode\devos-mono2\node_modules\tui-editor\dist
    at D:\mycode\devos-mono2\node_modules\postcss-load-config\src\index.js:91:15
    at D:\mycode\devos-mono2\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\mycode\devos-mono2\node_modules\postcss-loader\src\index.js:208:9

 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/components/MarkdownEditor/index.vue?vue&type=script&lang=ts& 10:0-40
 @ ./src/components/MarkdownEditor/index.vue?vue&type=script&lang=ts&
 @ ./src/components/MarkdownEditor/index.vue
 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/views/components-demo/markdown.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/markdown.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/markdown.vue
 @ ./src/router/modules/components.ts
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in D:/mycode/devos-mono2/node_modules/vue-image-crop-upload/upload-2.vue?vue&type=style&index=0&lang=css&

Module build failed (from D:/mycode/devos-mono2/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from D:/mycode/devos-mono2/node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: D:\mycode\devos-mono2\node_modules\vue-image-crop-upload
    at D:\mycode\devos-mono2\node_modules\postcss-load-config\src\index.js:91:15
    at D:\mycode\devos-mono2\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\mycode\devos-mono2\node_modules\postcss-loader\src\index.js:208:9

 @ D:/mycode/devos-mono2/node_modules/vue-image-crop-upload/upload-2.vue?vue&type=style&index=0&lang=css& 1:0-351 1:367-370 1:372-720 1:372-720
 @ D:/mycode/devos-mono2/node_modules/vue-image-crop-upload/upload-2.vue
 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/components/AvatarUpload/index.vue?vue&type=script&lang=ts&
 @ ./src/components/AvatarUpload/index.vue?vue&type=script&lang=ts&
 @ ./src/components/AvatarUpload/index.vue
 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/views/components-demo/avatar-upload.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/avatar-upload.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/avatar-upload.vue
 @ ./src/router/modules/components.ts
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in D:/mycode/devos-mono2/node_modules/vue2-dropzone/dist/vue2Dropzone.min.css

Module build failed (from D:/mycode/devos-mono2/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from D:/mycode/devos-mono2/node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: D:\mycode\devos-mono2\node_modules\vue2-dropzone\dist
    at D:\mycode\devos-mono2\node_modules\postcss-load-config\src\index.js:91:15
    at D:\mycode\devos-mono2\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\mycode\devos-mono2\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\mycode\devos-mono2\node_modules\postcss-loader\src\index.js:208:9

 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/components/Dropzone/index.vue?vue&type=script&lang=ts& 7:0-49
 @ ./src/components/Dropzone/index.vue?vue&type=script&lang=ts&
 @ ./src/components/Dropzone/index.vue
 @ D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--13-0!D:/mycode/devos-mono2/node_modules/thread-loader/dist/cjs.js!D:/mycode/devos-mono2/node_modules/babel-loader/lib!D:/mycode/devos-mono2/node_modules/ts-loader??ref--13-3!D:/mycode/devos-mono2/node_modules/cache-loader/dist/cjs.js??ref--0-0!D:/mycode/devos-mono2/node_modules/vue-loader/lib??vue-loader-options!./src/views/components-demo/dropzone.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/dropzone.vue?vue&type=script&lang=ts&
 @ ./src/views/components-demo/dropzone.vue
 @ ./src/router/modules/components.ts
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

> Executing task: yarn run build:prod <

yarn run v1.22.4









/  Building for production...

 ERROR  Failed to compile with 3 errors                                                                                           22:33:52
 error  in D:/mycode/devos-mono2/apps/web/src/components/DraggableKanban/index.vue

ERROR in D:/mycode/devos-mono2/apps/web/src/components/DraggableKanban/index.vue(26,2):
26:2 No overload matches this call.
  Overload 1 of 2, '(options: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>> & ThisType<...>): <VC extends VueClass<...>>(target: VC) => VC', gave the following error.
    Type 'typeof Draggable' is not assignable to type 'VueConstructor<Vue> | FunctionalComponentOptions<any, PropsDefinition<any>> | ComponentOptions<never, any, any, any, any, Record<...>> | AsyncComponentPromise<...> | AsyncComponentFactory<...>'.
      Type 'typeof Draggable' is not assignable to type 'VueConstructor<Vue>'.
        Types of parameters 'options' and 'options' are incompatible.
          Type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>> | undefined' is not assignable to type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never> | undefined'.
            Type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>' is not assignable to type 'ThisTypedComponentOptionsWithArrayProps<Vue, object, object, object, never>'.
              Type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>' is not assignable to type 'ComponentOptions<Vue, DataDef<object, Record<never, any>, Vue>, object, object, never[], Record<never, any>>'.
                Types of property 'props' are incompatible.
                  Type 'ArrayPropsDefinition<Record<string, any>> | RecordPropsDefinition<Record<string, any>> | undefined' is not assignable to type 'never[] | undefined'.
                    Type 'ArrayPropsDefinition<Record<string, any>>' is not assignable to type 'never[]'.
                      Type 'string' is not assignable to type 'never'.
  Overload 2 of 2, '(target: VueClass<Vue>): VueClass<Vue>', gave the following error.
    Argument of type '{ name: string; components: { Draggable: typeof Draggable; }; }' is not assignable to parameter of type 'VueClass<Vue>'.
      Object literal may only specify known properties, and 'name' does not exist in type 'VueClass<Vue>'.
    24 | import { Component, Prop, Vue } from 'vue-property-decorator'
    25 | 
  > 26 | @Component({
       |  ^
    27 |   name: 'DraggableKanban',
    28 |   components: {
    29 |     Draggable

 error  in D:/mycode/devos-mono2/apps/web/src/components/DraggableList/index.vue

ERROR in D:/mycode/devos-mono2/apps/web/src/components/DraggableList/index.vue(67,2):
67:2 No overload matches this call.
  Overload 1 of 2, '(options: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>> & ThisType<...>): <VC extends VueClass<...>>(target: VC) => VC', gave the following error.
    Type 'typeof Draggable' is not assignable to type 'VueConstructor<Vue> | FunctionalComponentOptions<any, PropsDefinition<any>> | ComponentOptions<never, any, any, any, any, Record<...>> | AsyncComponentPromise<...> | AsyncComponentFactory<...>'.
      Type 'typeof Draggable' is not assignable to type 'VueConstructor<Vue>'.
  Overload 2 of 2, '(target: VueClass<Vue>): VueClass<Vue>', gave the following error.
    Argument of type '{ name: string; components: { Draggable: typeof Draggable; }; }' is not assignable to parameter of type 'VueClass<Vue>'.
      Object literal may only specify known properties, and 'name' does not exist in type 'VueClass<Vue>'.
    65 | import { IArticleData } from '@/api/types'
    66 | 
  > 67 | @Component({
       |  ^
    68 |   name: 'DraggableList',
    69 |   components: {
    70 |     Draggable

 error  in D:/mycode/devos-mono2/node_modules/vuedraggable/src/vuedraggable.d.ts

ERROR in D:/mycode/devos-mono2/node_modules/vuedraggable/src/vuedraggable.d.ts(8,5):
8:5 Property 'element' in type 'Draggable' is not assignable to the same property in base type 'object & Record<never, any> & Vue'.
  Type 'string' is not assignable to type 'Element | null'.
     6 |     noTransitionOnDrag: boolean;
     7 | 
  >  8 |     element: string;
       |     ^
     9 | 
    10 |     tag: string;
    11 | 

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process terminated with exit code: 1
```

**Comment by Armour** [comment]
try the latest code.
