### ISSUE TITLE
node 16以上无法正常运行，报错

### ISSUE THREAD

**Issue by caizhehao** [Armour/vue-typescript-admin-template#233]
node 16以上无法正常运行，报错
{"message":"Not Found","error":{}}

**Comment by liuruij** [comment]
![image](https://user-images.githubusercontent.com/59092161/158500739-20dd128b-20a5-47fe-bb6d-dfe4aea755ee.png)
问题:启动报错，弹出microsoft visual c++ runtime library弹出框。
复现：
1、打开项目，运行yarn serve
2、mock运行中报错“npm run mock exited with code 1”
3、弹出弹窗，选择“重试”
4、结束进程
原因查找：
1、nodejs v16.x 或更高版本不支持 Fibers

**Comment by imoyao** [comment]
## 一种不优雅的解决办法
可以看看这个：
[ node 16.X 或更高版本 fibers 出错 is missing._我叫丨木木的博客-CSDN博客](https://blog.csdn.net/weixin_44149645/article/details/121362208)
```
[1] `~\node_modules\fibers\bin\win32-x64-93\fibers.node` is missing.
[1]
[1] Try running this to fix the issue: C:\Program Files\nodejs\node.exe ~\node_modules\fibers/build
[1] Error: Cannot find module '~\node_modules\fibers\bin\win32-x64-93\fibers'
[1] Require stack:


[1]     at runSyncOrAsync (~\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
[1]     at iterateNormalLoaders (~\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
[1] ~\node_modules\fibers\fibers.js:23
[1]             throw new Error('Missing binary. See message above.');
[1]                   ^
[1]
[1] Error: Missing binary. See message above.
[1]     at Object.<anonymous> (~\node_modules\fibers\fibers.js:23:9)
[1]     at Module._compile (node:internal/modules/cjs/loader:1105:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```
去下载`win32-x64-93_binding.node`并重命名为`fibers.node`，然后放置到指定目录。

**Comment by yyljwyy** [comment]
如果不想搞到脱发，建议使用NODE 14

**Comment by xliamh** [comment]
稳定安全，免费vpn, 支持chatgpt(https://monkeyff02.online/#/portal?c=ad01)
