### ISSUE TITLE
Error: Cannot find module '@babel/code-frame'

### ISSUE THREAD

**Issue by snowwolfjay** [Armour/vue-typescript-admin-template#87]
Using ts-node version 8.4.1, typescript version 3.6.2
[1]  ERROR  Error: Cannot find module '@babel/code-frame'
[1] Error: Cannot find module '@babel/code-frame'
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:692:17)
[1]     at require (internal/modules/cjs/helpers.js:25:18)
[1]     at Object.<anonymous> (G:\npm\node_modules\eslint\lib\formatters\codeframe.js:8:30)
[1]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[1]     at Module.load (internal/modules/cjs/loader.js:653:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[1]     at Module.require (internal/modules/cjs/loader.js:692:17)
[1]     at require (internal/modules/cjs/helpers.js:25:18)
[1]     at exports.loadModule (G:\apps\yx_manager\v1\ts\node_modules\@vue\cli-shared-utils\lib\module.js:51:12)
[1]     at api.chainWebpack.webpackConfig (G:\apps\yx_manager\v1\ts\node_modules\@vue\cli-plugin-eslint\index.js:63:17)
[1]     at webpackChainFns.forEach.fn (G:\apps\yx_manager\v1\ts\node_modules\@vue\cli-service\lib\Service.js:242:40)
[1]     at Array.forEach (<anonymous>)

_____
@babel/code-frame is installed

**Comment by Armour** [comment]
Should be fixed now.
